pre-commit hook validate that content is up-to-date

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -8,6 +8,17 @@
 # write`), it only checks if there is any issue and reports it.
 # Inspired by https://prettier.io/docs/en/precommit.html#option-6-shell-script
 
+# Validate that pre-commit and .git/hooks/pre-commit have the same content.
+# If content is not the same, do not commit.
+diff pre-commit .git/hooks/pre-commit > /dev/null
+if [[ $? == 1 ]]
+then
+  echo "Error: pre-commit and .git/hooks/pre-commit have different content."
+  echo "Aborting commit."
+  echo "Run 'cp pre-commit .git/hooks' to fix this."
+  exit 1
+fi
+
 get_staged_files() {
   ALL_FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g' | awk '/\.ts$|\.tsx$|\.js$|\.md|\.yml|\.yaml|\.css|\.json/')
   CODE_FILES=$(echo "$ALL_FILES" | awk '/\.ts$|\.tsx$|\.js$/')
